name: VSHN.tv workflow
on:
  schedule:
    # https://crontab.guru/#59_1_*_*_*/1
    - cron: '59 1 * * */1'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "VIDEOS"
          commit_message: "Updated readme with the latest videos"
          feed_list: "https://www.vshn.ch/general-rss.xml"
          max_post_count: 4
          readme_path: profile/README.md
